# Generated by Django 3.2.4 on 2022-01-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licensing_template", "0015_auto_20220124_1529"),
        ("licensing_template", "0015_auto_20220124_1647"),
    ]

    operations = []
